"use client";
import {useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";

export default function NyttPassord(){
 const [password,setPassword]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[client,setClient]=useState(null);
 useEffect(()=>{const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key){setError("Passordendring er ikke konfigurert.");return}const s=createClient(url,key);setClient(s);let mounted=true;async function recover(){try{const hash=new URLSearchParams(window.location.hash.replace(/^#/,"")),access=hash.get("access_token"),refresh=hash.get("refresh_token");if(access&&refresh){const {error:e}=await s.auth.setSession({access_token:access,refresh_token:refresh});if(e)throw e}const {data}=await s.auth.getSession();if(mounted)setReady(!!data.session);if(mounted&&!data.session)setError("Lenken er utløpt eller ugyldig. Be om en ny lenke fra Min side.")}catch{if(mounted)setError("Lenken er utløpt eller ugyldig. Be om en ny lenke fra Min side.")}}recover();return()=>{mounted=false}},[]);
 async function go(e){e.preventDefault();setError("");if(!client||!ready)return setError("Lenken er utløpt eller ugyldig. Be om en ny lenke fra Min side.");if(password.length<8||password.length>128)return setError("Passordet må være mellom 8 og 128 tegn.");setBusy(true);try{const {error:e}=await client.auth.updateUser({password});if(e){setError("Passordet kunne ikke endres. Be om en ny lenke fra Min side.");return}setMessage("Passordet er endret. Du kan nå gå tilbake og logge inn.");setReady(false)}finally{setBusy(false)}}
 return <main className="login"><form className="loginbox" onSubmit={go}><h1>Nytt passord</h1><p className="muted">Velg et nytt passord til kundekontoen din.</p><div className="field"><label>Nytt passord</label><input type="password" minLength={8} maxLength={128} required disabled={!ready||busy} value={password} onChange={e=>setPassword(e.target.value)}/></div>{error&&<p className="notice">{error}</p>}{message&&<p className="success">{message}</p>}<button className="btn" disabled={busy||!ready} style={{width:"100%",marginTop:14}}>{busy?"Lagrer …":"Lagre nytt passord"}</button><a href="/min-side" className="btn alt" style={{display:"block",textAlign:"center",marginTop:10}}>Til Min side</a></form></main>}
