import {sameOriginGuard} from "../../../../lib/requestGuard";
import {NextResponse} from "next/server";
import {getAdminUser,hasPermission} from "../../../../lib/auth";
import {db} from "../../../../lib/supabase";
import {DEFAULT_SITE_SETTINGS} from "../../site-settings/route";
import {safeSiteHref} from "../../../../lib/safeUrl";
import {safeEmail,safePhone} from "../../../../lib/contactValues";
function map(row){return {...DEFAULT_SITE_SETTINGS,heroEyebrow:row.hero_eyebrow??DEFAULT_SITE_SETTINGS.heroEyebrow,heroTitle:row.hero_title??DEFAULT_SITE_SETTINGS.heroTitle,heroText:row.hero_text??DEFAULT_SITE_SETTINGS.heroText,aboutTitle:row.about_title??DEFAULT_SITE_SETTINGS.aboutTitle,aboutText:row.about_text??DEFAULT_SITE_SETTINGS.aboutText,phone:row.phone??DEFAULT_SITE_SETTINGS.phone,email:row.email??DEFAULT_SITE_SETTINGS.email,orgNumber:row.org_number??DEFAULT_SITE_SETTINGS.orgNumber,location:row.location??DEFAULT_SITE_SETTINGS.location,seasonalTitle:row.seasonal_title||"",seasonalText:row.seasonal_text||"",seasonalCtaLabel:row.seasonal_cta_label||"",seasonalCtaHref:row.seasonal_cta_href||"",seasonalFrom:row.seasonal_from||null,seasonalUntil:row.seasonal_until||null,showSeasonal:row.show_seasonal===true,showServices:row.show_services!==false,showProjects:row.show_projects!==false,showAbout:row.show_about!==false,showSurvey:row.show_survey!==false};}
async function allowed(){return Boolean(await getAdminUser())&&await hasPermission("canManageProducts");}
export async function GET(){if(!(await allowed()))return NextResponse.json({error:"Ingen tilgang."},{status:403});const s=db();if(!s)return NextResponse.json({error:"Databasen er ikke tilgjengelig."},{status:503});const {data,error}=await s.from("site_settings").select("*").eq("id","main").maybeSingle();if(error){console.error("ADMIN SITE SETTINGS GET ERROR:",error);return NextResponse.json({error:"Innstillingene kunne ikke hentes."},{status:500})}if(!data)return NextResponse.json({settings:DEFAULT_SITE_SETTINGS});return NextResponse.json({settings:map(data)});}
function validDate(v){if(!v)return true;if(!/^\\d{4}-\\d{2}-\\d{2}$/.test(v))return false;const d=new Date(v+"T12:00:00Z");return !Number.isNaN(d.valueOf())&&d.toISOString().slice(0,10)===v}
export async function PUT(req){ const originError=sameOriginGuard(req); if(originError)return originError;if(!(await allowed()))return NextResponse.json({error:"Ingen tilgang."},{status:403});const v=await req.json();const phone=safePhone(v.phone);const email=safeEmail(v.email);if(String(v.phone||"").trim()&&!phone)return NextResponse.json({error:"Skriv inn et gyldig telefonnummer."},{status:400});if(String(v.email||"").trim()&&!email)return NextResponse.json({error:"Skriv inn en gyldig e-postadresse."},{status:400});if(!validDate(v.seasonalFrom)||!validDate(v.seasonalUntil))return NextResponse.json({error:"Sesongdatoene er ugyldige."},{status:400});if(v.seasonalFrom&&v.seasonalUntil&&v.seasonalUntil<v.seasonalFrom)return NextResponse.json({error:"Sluttdato for sesong kan ikke være før startdato."},{status:400});const href=String(v.seasonalCtaHref||"").trim();const safeHref=safeSiteHref(href);if(href&&!safeHref)return NextResponse.json({error:"Sesonglenken må være en intern lenke, en #seksjon eller en https-adresse."},{status:400});const s=db();if(!s)return NextResponse.json({error:"Databasen er ikke tilgjengelig."},{status:503});const record={id:"main",hero_eyebrow:String(v.heroEyebrow||"").slice(0,180),hero_title:String(v.heroTitle||"").slice(0,180),hero_text:String(v.heroText||"").slice(0,1200),about_title:String(v.aboutTitle||"").slice(0,180),about_text:String(v.aboutText||"").slice(0,1600),phone:phone||DEFAULT_SITE_SETTINGS.phone,email:email||DEFAULT_SITE_SETTINGS.email,org_number:String(v.orgNumber||"").slice(0,100),location:String(v.location||"").slice(0,180),seasonal_title:String(v.seasonalTitle||"").slice(0,180),seasonal_text:String(v.seasonalText||"").slice(0,1200),seasonal_cta_label:String(v.seasonalCtaLabel||"").slice(0,100),seasonal_cta_href:safeHref.slice(0,500),seasonal_from:v.seasonalFrom||null,seasonal_until:v.seasonalUntil||null,show_seasonal:v.showSeasonal===true,show_services:v.showServices!==false,show_projects:v.showProjects!==false,show_about:v.showAbout!==false,show_survey:v.showSurvey!==false,updated_at:new Date().toISOString()};const {data,error}=await s.from("site_settings").upsert(record).select("*").single();if(error)return NextResponse.json({error:"Innstillingene kunne ikke lagres."},{status:500});return NextResponse.json({settings:map(data)});}
