"use client";
import {useEffect,useMemo,useState} from "react";
import {fallbackProducts,nok,productPrice} from "../lib/catalog";

const emptyCustomer={name:"",email:"",phone:"",address:"",postalCode:"",city:"",note:"",deliveryWithinRadius:true};

export default function Home(){
 const [products,setProducts]=useState(fallbackProducts),[cart,setCart]=useState([]),[open,setOpen]=useState(false);
 const [customer,setCustomer]=useState(emptyCustomer),[fulfillment,setFulfillment]=useState("pickup");
 const [message,setMessage]=useState(null),[error,setError]=useState(""),[custom,setCustom]=useState("");
 useEffect(()=>{fetch("/api/products").then(r=>r.ok?r.json():null).then(d=>d?.products?.length&&setProducts(d.products)).catch(()=>{})},[]);
 const total=cart.reduce((s,i)=>s+i.unitPriceOre*i.quantity,0);
 function add(p,selected){const price=productPrice(p,selected);const key=p.id+JSON.stringify(selected);setCart(c=>{const found=c.find(i=>i.key===key);return found?c.map(i=>i.key===key?{...i,quantity:i.quantity+1}:i):[...c,{key,productId:p.id,name:p.name,selectedOptions:selected,unitPriceOre:price,quantity:1}]});setOpen(true)}
 async function order(e){e.preventDefault();setError("");const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderType:"order",customer,fulfillmentType:fulfillment,deliveryWithinRadius:customer.deliveryWithinRadius,items:cart.map(({productId,quantity,selectedOptions})=>({productId,quantity,selectedOptions}))})});const d=await r.json();if(!r.ok)return setError(d.error||"Noe gikk galt.");setMessage(d);setCart([])}
 async function customOrder(e){e.preventDefault();setError("");const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderType:"custom",customRequest:custom,customer,fulfillmentType:fulfillment,deliveryWithinRadius:customer.deliveryWithinRadius})});const d=await r.json();if(!r.ok)return setError(d.error||"Noe gikk galt.");setMessage(d);setCustom("")}
 return <main>
  <header className="top"><div className="wrap nav"><a className="brand" href="#"><span className="mark">AS</span><span>Aadland<br/>Service</span></a><nav className="links"><a href="#produkter">Produkter</a><a href="#slik">Slik fungerer det</a><a href="#om">Om oss</a><a href="#kontakt">Kontakt</a><button className="btn" onClick={()=>setOpen(true)}>Handlekurv ({cart.reduce((s,i)=>s+i.quantity,0)})</button></nav></div></header>
  <section className="wrap hero"><div><div className="kicker">Bygget i Bergen · laget for deg</div><h1>Kun<br/>muligheter.</h1><p>Bygg, renovering, vedlikehold og produkter på bestilling. Vi lager solide løsninger som tilpasses plassen og behovet ditt.</p><div style={{display:"flex",gap:12,marginTop:28}}><a className="btn" href="#produkter">Se produkter</a><a className="btn alt" href="#custom">Få noe laget</a></div></div><div className="heroCard"><span className="kicker">Aadland Service</span><strong>Laget på bestilling.</strong><p>Henting eller levering innen 15 km.</p></div></section>
  <section id="produkter" className="section"><div className="wrap"><div className="kicker">Produkter</div><h2>Velg, tilpass og bestill.</h2><p className="muted">Alle priser vises inkl. mva.</p><div className="grid">{products.filter(p=>p.active!==false).map(p=><Product key={p.id} p={p} add={add}/>)}</div></div></section>
  <section id="slik" className="section" style={{background:"#eee8dd"}}><div className="wrap"><div className="kicker">Slik fungerer det</div><h2>Fra idé til ferdig produkt.</h2><div className="grid">{["Velg eller beskriv","Vi bekrefter bestillingen","Hent eller få levert"].map((x,i)=><div className="card" key={x}><b>0{i+1}</b><h3>{x}</h3><p className="muted">{i===0?"Velg et produkt og tilpass størrelse og overflate, eller send en egen forespørsel.":i===1?"Vi går gjennom bestillingen og tar kontakt dersom noe må avklares.":"Store produkter hentes etter avtale eller leveres innenfor avtalt område."}</p></div>)}</div></div></section>
  <section id="custom" className="section"><div className="wrap"><div className="kicker">På bestilling</div><h2>Har du noe annet i tankene?</h2><form className="card" onSubmit={customOrder} style={{maxWidth:720}}><div className="field"><label>Beskriv hva du ønsker</label><textarea rows="6" required value={custom} onChange={e=>setCustom(e.target.value)} placeholder="Mål, materiale, bruk og andre ønsker …"/></div><CustomerFields customer={customer} setCustomer={setCustomer}/><button className="btn">Send forespørsel</button></form></div></section>
  <section id="om" className="section" style={{background:"#181613",color:"white"}}><div className="wrap"><div className="kicker">Om Aadland Service</div><h2>Praktiske løsninger. Solid utført.</h2><p style={{maxWidth:720,lineHeight:1.7,opacity:.8}}>Bygg, renovering, vedlikehold og produkter på bestilling i Bergen og omegn.</p></div></section>
  <footer id="kontakt" className="footer"><div className="wrap row"><div><b>Aadland Service</b><p>Bygg • Renovering • Vedlikehold • Hagearbeid</p></div><div><p>post@aadland-service.no</p><p>471 54 898</p><p>Org.nr. 937 781 873 MVA</p></div></div></footer>
  {cart.length>0&&<button className="cart" onClick={()=>setOpen(true)}>Handlekurv · {nok(total)}</button>}
  {open&&<div className="drawer" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><div className="drawerPanel"><div className="row"><h2>Handlekurv</h2><button className="btn alt" onClick={()=>setOpen(false)}>Lukk</button></div>{message&&<div className="success"><b>Bestilling mottatt</b><p>Ordrenummer: {message.orderNumber}</p><p>{message.message}</p></div>}{cart.map(i=><div className="card" key={i.key} style={{marginBottom:10}}><div className="row"><div><b>{i.name}</b><div className="muted">{Object.values(i.selectedOptions).join(" · ")}</div></div><b>{nok(i.unitPriceOre*i.quantity)}</b></div><div className="row" style={{marginTop:12}}><span>Antall: {i.quantity}</span><div><button className="btn alt" onClick={()=>setCart(c=>c.map(x=>x.key===i.key?{...x,quantity:x.quantity-1}:x).filter(x=>x.quantity>0))}>−</button> <button className="btn alt" onClick={()=>setCart(c=>c.map(x=>x.key===i.key?{...x,quantity:x.quantity+1}:x))}>+</button></div></div></div>)}<div className="row"><b>Totalt</b><b>{nok(total)}</b></div><div className="line"/><form onSubmit={order}><CustomerFields customer={customer} setCustomer={setCustomer}/><div className="field"><label>Henting eller levering</label><select value={fulfillment} onChange={e=>setFulfillment(e.target.value)}><option value="pickup">Henting</option><option value="delivery">Levering innen 15 km</option></select></div>{error&&<p className="notice">{error}</p>}<button className="btn" disabled={!cart.length}>Send bestilling</button></form></div></div>}
 </main>
}
function Product({p,add}){const initial=Object.fromEntries((p.options||[]).map(o=>[o.id,o.choices?.[0]?.value||""]));const [sel,setSel]=useState(initial);const price=useMemo(()=>productPrice(p,sel),[p,sel]);return <article className="card"><div className="kicker">{p.eyebrow}</div><h3>{p.name}</h3><p className="muted">{p.description}</p><div className="options">{(p.options||[]).map(o=><div className="field" key={o.id}><label>{o.label}</label><select value={sel[o.id]} onChange={e=>setSel(s=>({...s,[o.id]:e.target.value}))}>{o.choices.map(c=><option key={c.value} value={c.value}>{c.label}{c.extraOre?` (+${nok(c.extraOre)})`:""}</option>)}</select></div>)}</div><div className="row"><div className="price">{nok(price)}</div><button className="btn" onClick={()=>add(p,sel)}>Legg i kurv</button></div></article>}
function CustomerFields({customer,setCustomer}){const set=(k,v)=>setCustomer(c=>({...c,[k]:v}));return <div className="options"><div className="field"><label>Navn</label><input required value={customer.name} onChange={e=>set("name",e.target.value)}/></div><div className="field"><label>E-post</label><input type="email" required value={customer.email} onChange={e=>set("email",e.target.value)}/></div><div className="field"><label>Telefon</label><input required value={customer.phone} onChange={e=>set("phone",e.target.value)}/></div><div className="field"><label>Adresse</label><input value={customer.address} onChange={e=>set("address",e.target.value)}/></div><div className="field"><label>Postnummer</label><input value={customer.postalCode} onChange={e=>set("postalCode",e.target.value)}/></div><div className="field"><label>Sted</label><input value={customer.city} onChange={e=>set("city",e.target.value)}/></div><div className="field"><label>Merknad</label><textarea rows="3" value={customer.note} onChange={e=>set("note",e.target.value)}/></div></div>}
