"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
const orderStatus={new:"Mottatt",confirmed:"Bekreftet",processing:"Under behandling",completed:"Fullført",cancelled:"Kansellert"};
const rentalStatus={new:"Mottatt",confirmed:"Bekreftet",active:"Pågående",returned:"Returnert",completed:"Fullført",cancelled:"Kansellert"};
const paymentStatus={unpaid:"Ikke betalt",pending:"Avventer betaling",authorized:"Reservert",paid:"Betalt",refunded:"Refundert"};
const date=v=>v?new Intl.DateTimeFormat("nb-NO").format(new Date(v+"T12:00:00")):"";
const kr=o=>new Intl.NumberFormat("nb-NO",{style:"currency",currency:"NOK",maximumFractionDigits:0}).format((Number(o)||0)/100);
export default function MinSide(){const [mode,setMode]=useState("login"),[form,setForm]=useState({name:"",email:"",phone:"",address:"",password:""}),[data,setData]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[info,setInfo]=useState("");
async function load(){try{const r=await fetch("/api/customer/me"),d=await r.json();if(r.ok)setData(d);else setData(null)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
async function submit(e){e.preventDefault();setBusy(true);setError("");setInfo("");try{const r=await fetch("/api/customer/"+(mode==="login"?"login":"register"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),d=await r.json();if(!r.ok){setError(d.error||"Kunne ikke fortsette.");return}if(d.verificationRequired){setInfo(d.message||"Bekreft e-postadressen før du logger inn.");setMode("login");setForm({...form,password:""});return}await load()}finally{setBusy(false)}}
async function resetPassword(){setError("");setInfo("");if(!form.email.trim()){setError("Skriv inn e-postadressen din først.");return}setBusy(true);try{const r=await fetch("/api/customer/reset-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:form.email})}),d=await r.json();setInfo(d.message||"Hvis e-postadressen er registrert, sender vi en lenke.")}catch{setError("Kunne ikke sende lenken akkurat nå.")}finally{setBusy(false)}}
async function logout(){await fetch("/api/customer/logout",{method:"POST"});setData(null);setMode("login")}
if(loading)return <main style={{maxWidth:900,margin:"0 auto",padding:"50px 20px"}}><p>Laster …</p></main>;
if(!data)return <main style={{maxWidth:620,margin:"0 auto",padding:"50px 20px 90px"}}><Link href="/">← Aadland Service</Link><div className="kicker" style={{marginTop:28}}>MIN SIDE</div><h1>{mode==="login"?"Logg inn":"Opprett kundekonto"}</h1><p>Det er frivillig å ha konto. Med Min side kan du samle kjøp og utleie på ett sted.</p><form className="card" onSubmit={submit}>{mode==="register"&&<><div className="field"><label>Navn</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>Telefon</label><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div className="field"><label>Adresse</label><input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></div></>}<div className="field"><label>E-post</label><input required type="email" autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div className="field"><label>Passord</label><input required minLength={8} type="password" autoComplete={mode==="login"?"current-password":"new-password"} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div>{error&&<p className="notice">{error}</p>}{info&&<p className="success">{info}</p>}<button className="btn" disabled={busy}>{busy?"Vent litt …":mode==="login"?"Logg inn":"Opprett konto"}</button></form>{mode==="login"&&<button type="button" className="btn alt" style={{marginTop:12,marginRight:8}} disabled={busy} onClick={resetPassword}>Glemt passord?</button>}<button className="btn alt" style={{marginTop:12}} onClick={()=>{setError("");setInfo("");setMode(mode==="login"?"register":"login")}}>{mode==="login"?"Ny kunde? Opprett konto":"Har du konto? Logg inn"}</button></main>;
return <main style={{maxWidth:1000,margin:"0 auto",padding:"50px 20px 90px"}}><Link href="/">← Aadland Service</Link><div style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"end",marginTop:28,flexWrap:"wrap"}}><div><div className="kicker">MIN SIDE</div><h1>Hei, {data.customer.name||"kunde"}</h1><p>{data.customer.email}</p></div><button className="btn alt" onClick={logout}>Logg ut</button></div><section style={{marginTop:35}}><h2>Bestillinger</h2>{!data.orders.length?<p>Ingen bestillinger knyttet til kontoen ennå.</p>:<div className="grid">{data.orders.map(o=><article className="card" key={o.id}><b>{o.order_number}</b><p>Status: {orderStatus[o.status]||o.status}</p><p>{kr(o.total_ore)} · Betaling: {paymentStatus[o.payment_status]||o.payment_status||"Ikke registrert"}</p></article>)}</div>}</section><section style={{marginTop:35}}><h2>Utleie</h2>{!data.rentals.length?<p>Ingen utleier knyttet til kontoen ennå.</p>:<div className="grid">{data.rentals.map(r=><article className="card" key={r.id}><b>{r.rental_items?.name||r.booking_number}</b><p>{date(r.start_date)} – {date(r.end_date)}</p><p>Status: {rentalStatus[r.status]||r.status} · {kr(r.total_ore)}</p></article>)}</div>}</section></main>}
