"use client";
import {useEffect,useState} from "react";
const kr=o=>new Intl.NumberFormat("nb-NO",{style:"currency",currency:"NOK",maximumFractionDigits:0}).format((Number(o)||0)/100);
export default function Utleie(){
 const [dates,setDates]=useState({start:"",end:""}),[items,setItems]=useState([]),[loading,setLoading]=useState(false),[chosen,setChosen]=useState(null),[customer,setCustomer]=useState({name:"",email:"",phone:"",address:""}),[msg,setMsg]=useState(""),[err,setErr]=useState("");
 async function load(){setLoading(true);const q=dates.start&&dates.end?"?start="+dates.start+"&end="+dates.end:"";const r=await fetch("/api/rental"+q);const d=await r.json();setItems(d.items||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(dates.start&&dates.end&&dates.end>=dates.start)load()},[dates.start,dates.end]);
 async function book(e){e.preventDefault();setErr("");setMsg("");const r=await fetch("/api/rental-bookings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({itemId:chosen.id,startDate:dates.start,endDate:dates.end,customer,termsVersion:"2026-09"})});const d=await r.json();if(!r.ok){setErr(d.error||"Kunne ikke sende booking.");return;}setMsg("Takk! Booking "+d.bookingNumber+" er mottatt. Pris "+kr(d.totalOre)+(d.depositOre?" + depositum "+kr(d.depositOre):"")+".");setChosen(null);load()}
 return <main style={{maxWidth:1180,margin:"0 auto",padding:"40px 20px 80px"}}><a href="/">← Aadland Service</a><h1>Utleie</h1><p>Velg datoene du trenger utstyret. Tilgjengelighet og pris beregnes automatisk.</p>
 <div className="card" style={{display:"flex",gap:16,flexWrap:"wrap",margin:"24px 0"}}><label>Fra<br/><input type="date" value={dates.start} onChange={e=>setDates({...dates,start:e.target.value,end:dates.end&&dates.end<e.target.value?e.target.value:dates.end})}/></label><label>Til<br/><input type="date" min={dates.start} value={dates.end} onChange={e=>setDates({...dates,end:e.target.value})}/></label></div>
 {msg&&<p className="success">{msg}</p>}{loading?<p>Laster …</p>:<div className="grid">{items.map(item=><article className="card" key={item.id}>{item.imageUrls?.[0]&&<img src={item.imageUrls[0]} alt="" style={{width:"100%",height:220,objectFit:"cover",borderRadius:12}}/>}<h2>{item.name}</h2><p>{item.description}</p><p><b>{dates.start&&dates.end&&item.pricing?kr(item.pricing.totalOre):kr(item.dailyPriceOre)+" / dag"}</b>{item.depositOre?<> · Depositum {kr(item.depositOre)}</>:null}</p>{dates.start&&dates.end?<button className="btn" disabled={!item.available} onClick={()=>setChosen(item)}>{item.available?"Velg":"Ikke tilgjengelig"}</button>:<small>Velg dato for å se tilgjengelighet.</small>}</article>)}</div>}
 {chosen&&<form className="card" onSubmit={book} style={{marginTop:30}}><h2>Book {chosen.name}</h2><p>{dates.start} – {dates.end} · <b>{kr(chosen.pricing?.totalOre)}</b></p><div className="field"><label>Navn</label><input required value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})}/></div><div className="field"><label>Telefon</label><input required type="tel" value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/></div><div className="field"><label>E-post</label><input required type="email" value={customer.email} onChange={e=>setCustomer({...customer,email:e.target.value})}/></div><div className="field"><label>Adresse</label><input value={customer.address} onChange={e=>setCustomer({...customer,address:e.target.value})}/></div><label><input type="checkbox" required/> Jeg godtar vilkårene for utleie.</label>{err&&<p className="notice">{err}</p>}<div style={{display:"flex",gap:10,marginTop:18}}><button className="btn">Send booking</button><button type="button" className="btn alt" onClick={()=>setChosen(null)}>Avbryt</button></div></form>}
 </main>
}