"use client";
import {useEffect,useState} from "react";
const kr=o=>new Intl.NumberFormat("nb-NO",{style:"currency",currency:"NOK",maximumFractionDigits:0}).format((Number(o)||0)/100);
export default function Utleie(){const [dates,setDates]=useState({start:"",end:""}),[items,setItems]=useState([]),[loading,setLoading]=useState(false),[chosen,setChosen]=useState(null),[customer,setCustomer]=useState({name:"",email:"",phone:"",address:""}),[accepted,setAccepted]=useState(false),[msg,setMsg]=useState(""),[err,setErr]=useState(""),[setup,setSetup]=useState(false);
async function load(){setLoading(true);setErr("");try{const q=dates.start&&dates.end?"?start="+dates.start+"&end="+dates.end:"",r=await fetch("/api/rental"+q),d=await r.json();if(!r.ok)throw new Error(d.error||"Utleie kunne ikke lastes.");setItems(d.items||[]);setSetup(!!d.setupRequired)}catch(e){setErr(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);useEffect(()=>{if(dates.start&&dates.end&&dates.end>=dates.start)load()},[dates.start,dates.end]);
async function book(e){e.preventDefault();setErr("");setMsg("");const r=await fetch("/api/rental-bookings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({itemId:chosen.id,startDate:dates.start,endDate:dates.end,customer,fulfillment,acceptedTerms:accepted,termsVersion:"2026-09"})}),d=await r.json();if(!r.ok){setErr(d.error||"Kunne ikke sende booking.");return}setMsg("Takk! Booking "+d.bookingNumber+" er mottatt. Leiepris "+kr(d.totalOre)+(d.depositOre?" + depositum "+kr(d.depositOre):"")+".");setChosen(null);setAccepted(false);load()}
return <main style={{maxWidth:1180,margin:"0 auto",padding:"40px 20px 80px"}}><a href="/">← Aadland Service</a><div className="kicker" style={{marginTop:28}}>AADLAND SERVICE · UTLEIE</div><h1>Lei utstyr når du trenger det.</h1><p>Velg perioden først. Da ser du hva som er ledig og hva leien koster før du sender forespørselen.</p>
<div className="card" style={{display:"flex",gap:16,flexWrap:"wrap",margin:"24px 0"}}><label>Fra<br/><input type="date" min={today} value={dates.start} onChange={e=>setDates({...dates,start:e.target.value,end:dates.end&&dates.end<e.target.value?e.target.value:dates.end})}/></label><label>Til<br/><input type="date" min={dates.start} value={dates.end} onChange={e=>setDates({...dates,end:e.target.value})}/></label></div>
{msg&&<p className="success">{msg}</p>}{err&&<p className="notice">{err}</p>}{setup&&<p className="muted">Utleie åpner snart.</p>}{loading?<p>Laster …</p>:!items.length&&!setup?<div className="card"><h2>Ingen utstyr publisert ennå</h2><p>Utleieutstyr kommer her når det er klart.</p></div>:<div className="grid">{items.map(item=><article className="card" key={item.id}>{item.imageUrls?.[0]&&<img src={item.imageUrls[0]} alt={item.name} style={{width:"100%",height:220,objectFit:"cover",borderRadius:12}}/>}<h2>{item.name}</h2><p>{item.description}</p><p><b>{dates.start&&dates.end&&item.pricing?kr(item.pricing.totalOre):kr(item.dailyPriceOre)+" / dag"}</b>{item.depositOre?<> · Depositum {kr(item.depositOre)}</>:null}</p>{dates.start&&dates.end?<button className="btn" disabled={!item.available} onClick={()=>{setChosen(item);setErr("")}}>{item.available?"Velg":"Opptatt i perioden"}</button>:<small>Velg dato for å se tilgjengelighet og totalpris.</small>}</article>)}</div>}
{chosen&&<form className="card" onSubmit={book} style={{marginTop:30}}><div className="kicker">BOOKINGFORESPØRSEL</div><h2>{chosen.name}</h2><p>{dates.start} – {dates.end} · <b>{kr(chosen.pricing?.totalOre)}</b>{chosen.depositOre?" + depositum "+kr(chosen.depositOre):""}</p><div className="field"><label>Navn</label><input required value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})}/></div><div className="field"><label>Telefon</label><input required type="tel" value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/></div><div className="field"><label>E-post</label><input required type="email" value={customer.email} onChange={e=>setCustomer({...customer,email:e.target.value})}/></div><div className="field"><label>Adresse</label><input value={customer.address} onChange={e=>setCustomer({...customer,address:e.target.value})}/></div><div className="field"><label>Henting / levering</label><select value={fulfillment} onChange={e=>setFulfillment(e.target.value)}>{chosen.pickupAvailable&&<option value="pickup">Jeg henter selv</option>}{chosen.deliveryAvailable&&<option value="delivery">Jeg ønsker levering</option>}</select></div><label><input type="checkbox" required checked={accepted} onChange={e=>setAccepted(e.target.checked)}/> Jeg godtar vilkårene for utleie.</label><div style={{display:"flex",gap:10,marginTop:18}}><button className="btn">Send bookingforespørsel</button><button type="button" className="btn alt" onClick={()=>setChosen(null)}>Avbryt</button></div></form>}</main>}
