import {NextResponse} from "next/server";
import {getAdminUser,hasPermission} from "../../../../lib/auth";
import {db,fromDbRentalItem} from "../../../../lib/supabase";
function slugify(v){return String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}
async function allowed(){return (await getAdminUser()) && (await hasPermission("canManageProducts"))}
function record(b){return {name:String(b.name||"").trim(),description:String(b.description||"").trim(),image_urls:Array.isArray(b.imageUrls)?b.imageUrls:[],status:b.status||"available",quantity:Math.max(1,Number(b.quantity)||1),daily_price_ore:Math.max(0,Number(b.dailyPriceOre)||0),weekend_price_ore:b.weekendPriceOre==null?null:Math.max(0,Number(b.weekendPriceOre)||0),weekly_price_ore:b.weeklyPriceOre==null?null:Math.max(0,Number(b.weeklyPriceOre)||0),long_term_days:b.longTermDays?Math.max(1,Number(b.longTermDays)):null,long_term_discount_percent:Math.max(0,Math.min(100,Number(b.longTermDiscountPercent)||0)),deposit_ore:Math.max(0,Number(b.depositOre)||0),buffer_days:Math.max(0,Number(b.bufferDays)||0),delivery_available:!!b.deliveryAvailable,pickup_available:b.pickupAvailable!==false,active:b.active!==false,sort_order:Number(b.sortOrder)||0}}
export async function GET(){if(!(await allowed()))return NextResponse.json({error:"Ingen tilgang."},{status:403});const s=db();if(!s)return NextResponse.json({error:"Databasen er ikke tilgjengelig."},{status:500});const {data,error}=await s.from("rental_items").select("*").order("sort_order").order("created_at");if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({items:(data||[]).map(fromDbRentalItem)})}
export async function POST(req){if(!(await allowed()))return NextResponse.json({error:"Ingen tilgang."},{status:403});const b=await req.json();if(!String(b.name||"").trim())return NextResponse.json({error:"Utstyret må ha navn."},{status:400});const s=db(),r=record(b);r.slug=slugify(b.name)+"-"+Date.now().toString().slice(-5);const {data,error}=await s.from("rental_items").insert(r).select("*").single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({item:fromDbRentalItem(data)})}
export async function PATCH(req){if(!(await allowed()))return NextResponse.json({error:"Ingen tilgang."},{status:403});const b=await req.json();if(!b.id)return NextResponse.json({error:"Utstyr mangler."},{status:400});const s=db();const {data,error}=await s.from("rental_items").update(record(b)).eq("id",b.id).select("*").single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({item:fromDbRentalItem(data)})}
export async function DELETE(req){if(!(await allowed()))return NextResponse.json({error:"Ingen tilgang."},{status:403});const {id}=await req.json();if(!id)return NextResponse.json({error:"Utstyr mangler."},{status:400});const s=db();const {error}=await s.from("rental_items").delete().eq("id",id);if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true})}
