import { NextResponse } from "next/server";
import { getAdminUser, hasPermission } from "../../../../lib/auth";
import { db, fromDbRentalItem } from "../../../../lib/supabase";
function slugify(v){return String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}
async function allowed(){return (await getAdminUser()) && (await hasPermission("canManageProducts"))}
function ore(v){if(v===""||v==null)return null;const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.round(n)):null}
function record(b){return {name:String(b.name||"").trim().slice(0,180),description:String(b.description||"").trim().slice(0,8000),image_urls:Array.isArray(b.imageUrls)?b.imageUrls.map(x=>String(x||"").trim().slice(0,2000)).filter(Boolean).slice(0,30):[],status:["available","unavailable","hidden","maintenance"].includes(b.status)?b.status:"available",quantity:Math.max(1,Math.round(Number(b.quantity)||1)),daily_price_ore:ore(b.dailyPriceOre)||0,weekend_price_ore:ore(b.weekendPriceOre),weekly_price_ore:ore(b.weeklyPriceOre),long_term_days:b.longTermDays?Math.max(1,Math.round(Number(b.longTermDays))):null,long_term_discount_percent:Math.max(0,Math.min(100,Number(b.longTermDiscountPercent)||0)),deposit_ore:ore(b.depositOre)||0,buffer_days:Math.max(0,Math.round(Number(b.bufferDays)||0)),delivery_available:!!b.deliveryAvailable,pickup_available:b.pickupAvailable!==false,active:b.active!==false,sort_order:Math.round(Number(b.sortOrder)||0)}}
export async function GET(){if(!(await allowed()))return NextResponse.json({error:"Ingen tilgang."},{status:403});const s=db();if(!s)return NextResponse.json({error:"Databasen er ikke tilgjengelig."},{status:503});const {data,error}=await s.from("rental_items").select("*").order("sort_order").order("created_at");if(error){if(error.code==="42P01")return NextResponse.json({items:[],setupRequired:true});return NextResponse.json({error:error.message},{status:500})}return NextResponse.json({items:(data||[]).map(fromDbRentalItem)})}
export async function POST(req){if(!(await allowed()))return NextResponse.json({error:"Ingen tilgang."},{status:403});const b=await req.json();if(!String(b.name||"").trim())return NextResponse.json({error:"Utstyret må ha navn."},{status:400});const s=db();if(!s)return NextResponse.json({error:"Databasen er ikke tilgjengelig."},{status:503});const r=record(b);r.slug=slugify(b.name)+"-"+Date.now().toString().slice(-6);const {data,error}=await s.from("rental_items").insert(r).select("*").single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({item:fromDbRentalItem(data)})}
export async function PATCH(req){if(!(await allowed()))return NextResponse.json({error:"Ingen tilgang."},{status:403});const b=await req.json();if(!b.id)return NextResponse.json({error:"Utstyr mangler."},{status:400});const s=db();if(!s)return NextResponse.json({error:"Databasen er ikke tilgjengelig."},{status:503});const {data,error}=await s.from("rental_items").update({...record(b),updated_at:new Date().toISOString()}).eq("id",b.id).select("*").single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({item:fromDbRentalItem(data)})}
export async function DELETE(req){if(!(await allowed()))return NextResponse.json({error:"Ingen tilgang."},{status:403});const {id}=await req.json();if(!id)return NextResponse.json({error:"Utstyr mangler."},{status:400});const s=db();if(!s)return NextResponse.json({error:"Databasen er ikke tilgjengelig."},{status:503});const {count,error:countError}=await s.from("rental_bookings").select("id",{count:"exact",head:true}).eq("rental_item_id",id);if(countError)return NextResponse.json({error:"Bookinghistorikken kunne ikke kontrolleres."},{status:500});if((count||0)>0)return NextResponse.json({error:"Utstyret har bookinghistorikk og kan derfor ikke slettes. Sett det som skjult i stedet."},{status:409});const {error}=await s.from("rental_items").delete().eq("id",id);if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true})}
