"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import styles from "./drawing.module.css";

const GRID=100, VIEW=8000, STORE="aadlandDrawingsV2";
const catalog=[
 {group:"Bygg",items:[["door","Dør",900,100],["sliding","Skyvedør",1800,100],["window","Vindu",1200,100],["opening","Åpning",1000,100],["stairs","Trapp",900,2500],["post","Stolpe",98,98]]},
 {group:"Bad",items:[["toilet","Toalett",400,700],["walltoilet","Vegghengt toalett",400,600],["shower","Dusj",900,900],["bath","Badekar",750,1700],["sink","Servant",600,500],["washer","Vaskemaskin",600,600]]},
 {group:"Kjøkken",items:[["base","Benkeskap",600,600],["wallcab","Overskap",600,350],["tallcab","Høyskap",600,600],["fridge","Kjøleskap",600,600],["oven","Komfyr",600,600],["dishwasher","Oppvaskmaskin",600,600],["island","Kjøkkenøy",1800,900]]},
 {group:"Møbler",items:[["sofa","Sofa",2200,900],["table","Spisebord",1800,900],["chair","Stol",500,500],["bed","Seng",1800,2000],["wardrobe","Garderobe",1200,600],["tv","TV",1200,120]]},
 {group:"Ute",items:[["deck","Terrassefelt",3000,3000],["railing","Rekkverk",2000,100],["screen","Levegg",1800,100],["bench","Benk",1800,500],["planter","Plantekasse",1200,450]]}
];
const flat=catalog.flatMap(g=>g.items), labelFor=t=>flat.find(x=>x[0]===t)?.[1]||t;
const uid=()=>globalThis.crypto?.randomUUID?.()||Math.random().toString(36).slice(2);
const snapTo=(n,size=GRID)=>Math.round(n/size)*size;
const len=w=>Math.round(Math.hypot(w.x2-w.x1,w.y2-w.y1));
const angle=w=>Math.round(Math.atan2(w.y2-w.y1,w.x2-w.x1)*180/Math.PI*10)/10;
const wallOffset=(o,w)=>{const dx=w.x2-w.x1,dy=w.y2-w.y1,L=Math.hypot(dx,dy)||1;return Math.round(((o.x+o.w/2-w.x1)*dx+(o.y+o.h/2-w.y1)*dy)/L)};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const dim=w=>{const dx=w.x2-w.x1,dy=w.y2-w.y1,L=Math.hypot(dx,dy)||1,nx=-dy/L,ny=dx/L,off=150;return {ax:w.x1+nx*off,ay:w.y1+ny*off,bx:w.x2+nx*off,by:w.y2+ny*off,nx,ny,mx:(w.x1+w.x2)/2+nx*(off+70),my:(w.y1+w.y2)/2+ny*(off+70)}};

const initial=()=>({id:uid(),name:"Ny tegning",projectId:"",customer:"",address:"",notes:"",walls:[],items:[],measurements:[],snapSize:50,showGrid:true,scale:"1:50",zoom:1});
const wallTypes=new Set(["door","sliding","window","opening","railing","screen"]);
function nearestWall(o,walls){
 let best=null;
 for(const w of walls){const dx=w.x2-w.x1,dy=w.y2-w.y1,L2=dx*dx+dy*dy;if(!L2)continue;let t=((o.x-w.x1)*dx+(o.y-w.y1)*dy)/L2;t=Math.max(0,Math.min(1,t));const x=w.x1+t*dx,y=w.y1+t*dy,dist=Math.hypot(o.x-x,o.y-y);if(!best||dist<best.dist)best={wall:w,x,y,dist,t};}
 return best;
}

export default function DrawingClient(){
 const [docs,setDocs]=useState([]),[doc,setDoc]=useState(initial),[selected,setSelected]=useState(null),[draft,setDraft]=useState(null),[tool,setTool]=useState("select"),[drag,setDrag]=useState(null),[history,setHistory]=useState([]),[future,setFuture]=useState([]),[message,setMessage]=useState(""),[projects,setProjects]=useState([]),[measureDraft,setMeasureDraft]=useState(null),[wallDrag,setWallDrag]=useState(null),[pan,setPan]=useState({x:0,y:0}),[panning,setPanning]=useState(null);
 const svg=useRef(null);
 useEffect(()=>{try{const d=JSON.parse(localStorage.getItem(STORE)||"[]");if(d.length){setDocs(d);setDoc(d[0])}else{const old=JSON.parse(localStorage.getItem("aadlandDrawing")||"null");if(old)setDoc({...initial(),...old})}}catch{} fetch("/api/admin/projects").then(r=>r.ok?r.json():null).then(x=>setProjects(x?.projects||[])).catch(()=>{});},[]);
 const persistLocal=next=>{const list=[...docs.filter(x=>x.id!==next.id),next];setDocs(list);localStorage.setItem(STORE,JSON.stringify(list))};
 const persist=async(next=doc)=>{persistLocal(next);if(!next.projectId){setMessage("Lagret på enheten");setTimeout(()=>setMessage(""),1800);return}setMessage("Lagrer…");try{const body={id:next.serverId,projectId:next.projectId,name:next.name,customer:next.customer,address:next.address,notes:next.notes,drawingData:{...next,serverId:undefined}};const r=await fetch("/api/admin/project-drawings",{method:next.serverId?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),x=await r.json();if(r.ok&&x.drawing){const saved={...next,serverId:x.drawing.id};setDoc(saved);persistLocal(saved);setMessage("Lagret i oppdraget")}else if(x.setupRequired)setMessage("Lokalt lagret · database ikke aktivert");else setMessage("Lokalt lagret · serverfeil")}catch{setMessage("Lokalt lagret · server utilgjengelig")}setTimeout(()=>setMessage(""),2600)};
 const checkpoint=()=>setHistory(h=>[...h.slice(-24),JSON.stringify(doc)]);
 const syncMounted=(walls,items)=>items.map(o=>{if(!o.wallId)return o;const w=walls.find(x=>x.id===o.wallId);if(!w)return {...o,wallId:null};const L=len(w),off=clamp(wallOffset(o,w),0,L),a=Math.atan2(w.y2-w.y1,w.x2-w.x1),cx=w.x1+Math.cos(a)*off,cy=w.y1+Math.sin(a)*off;return {...o,x:cx-o.w/2,y:cy-o.h/2,rot:a*180/Math.PI}});
 const mutate=fn=>{checkpoint();setFuture([]);setDoc(d=>fn(d))};
 const undo=()=>{const last=history.at(-1);if(!last)return;setFuture(f=>[JSON.stringify(doc),...f].slice(0,25));setDoc(JSON.parse(last));setHistory(h=>h.slice(0,-1));setSelected(null)};
 const redo=()=>{const next=future[0];if(!next)return;setHistory(h=>[...h.slice(-24),JSON.stringify(doc)]);setDoc(JSON.parse(next));setFuture(f=>f.slice(1));setSelected(null)};
 const viewSize=VIEW/(doc.zoom||1);
 const point=e=>{const r=svg.current.getBoundingClientRect();return{x:pan.x+(e.clientX-r.left)*viewSize/r.width,y:pan.y+(e.clientY-r.top)*viewSize/r.height}};
 const zoomBy=delta=>setDoc(d=>({...d,zoom:clamp((d.zoom||1)+delta,.5,3)}));
 const fitView=()=>{setPan({x:0,y:0});setDoc(d=>({...d,zoom:1}))};
 const startPan=e=>{if(tool!=="pan")return;setPanning({cx:e.clientX,cy:e.clientY,x:pan.x,y:pan.y})};
 const movePan=e=>{if(!panning)return;const r=svg.current.getBoundingClientRect();setPan({x:panning.x-(e.clientX-panning.cx)*viewSize/r.width,y:panning.y-(e.clientY-panning.cy)*viewSize/r.height})};
 const newDoc=()=>{const d=initial();setDoc(d);setSelected(null);setHistory([]);setFuture([])};
 const openDoc=id=>{const d=docs.find(x=>x.id===id);if(d){setDoc(d);setSelected(null);setHistory([]);setFuture([])}};
 const loadProjectDrawings=async projectId=>{if(!projectId)return;try{const r=await fetch("/api/admin/project-drawings?projectId="+encodeURIComponent(projectId)),x=await r.json();if(!r.ok||x.setupRequired)return;const incoming=(x.drawings||[]).map(row=>({...initial(),...(row.drawingData||{}),serverId:row.id,projectId:row.projectId,name:row.name,customer:row.customer,address:row.address,notes:row.notes}));if(incoming.length){const merged=[...docs];for(const d of incoming){const i=merged.findIndex(x=>x.serverId===d.serverId);if(i>=0)merged[i]=d;else merged.push(d)}setDocs(merged);localStorage.setItem(STORE,JSON.stringify(merged));setMessage(incoming.length+" tegning(er) hentet fra oppdrag");setTimeout(()=>setMessage(""),2200)}}catch{}};
 const changeProject=e=>{const projectId=e.target.value;setDoc(d=>({...d,projectId}));if(projectId)loadProjectDrawings(projectId)};
 const makeRoom=()=>{const w=Number(prompt("Romlengde i mm","4000")),h=Number(prompt("Rombredde i mm","3000"));if(w<300||h<300)return;const x=1000,y=1000,t=98,H=2400;mutate(d=>({...d,walls:[...d.walls,{id:uid(),x1:x,y1:y,x2:x+w,y2:y,t,h:H},{id:uid(),x1:x+w,y1:y,x2:x+w,y2:y+h,t,h:H},{id:uid(),x1:x+w,y1:y+h,x2:x,y2:y+h,t,h:H},{id:uid(),x1:x,y1:y+h,x2:x,y2:y,t,h:H}]}))};
 const addItem=(type,w,h)=>mutate(d=>({...d,items:[...d.items,{id:uid(),type,x:1800,y:1600,w,h,rot:0}]}));
 const sel=useMemo(()=>selected?.kind==="wall"?doc.walls.find(x=>x.id===selected.id):selected?.kind==="item"?doc.items.find(x=>x.id===selected.id):null,[selected,doc]);
 const update=(key,value)=>{const n=Number(value);if(!Number.isFinite(n))return;mutate(d=>selected?.kind==="item"?{...d,items:d.items.map(o=>{if(o.id!==selected.id)return o;if(key==="wallOffset"&&o.wallId){const w=d.walls.find(x=>x.id===o.wallId);if(!w)return o;const L=len(w),off=clamp(n,0,L),a=Math.atan2(w.y2-w.y1,w.x2-w.x1),cx=w.x1+Math.cos(a)*off,cy=w.y1+Math.sin(a)*off;return{...o,x:cx-o.w/2,y:cy-o.h/2,rot:a*180/Math.PI}}return{...o,[key]:n}})}:{...d,walls:d.walls.map(w=>{if(w.id!==selected.id)return w;if(key==="len"||key==="angle"){const L=key==="len"?n:len(w),A=(key==="angle"?n:angle(w))*Math.PI/180;return{...w,x2:w.x1+L*Math.cos(A),y2:w.y1+L*Math.sin(A)}}return{...w,[key]:n}});return {...d,walls,items:syncMounted(walls,d.items)}} )};
 const remove=()=>{checkpoint();setFuture([]);setDoc(d=>selected?.kind==="wall"?{...d,walls:d.walls.filter(x=>x.id!==selected.id),items:d.items.map(o=>o.wallId===selected.id?{...o,wallId:null}:o)}:{...d,items:d.items.filter(x=>x.id!==selected.id)});setSelected(null)};
 const flipDoor=()=>{if(selected?.kind!=="item"||!sel||sel.type!=="door")return;mutate(d=>({...d,items:d.items.map(o=>o.id===sel.id?{...o,flip:!o.flip}:o)}))};
 const detach=()=>{if(selected?.kind!=="item"||!sel)return;mutate(d=>({...d,items:d.items.map(o=>o.id===sel.id?{...o,wallId:null}:o)}))};
 const duplicate=()=>{if(selected?.kind!=="item"||!sel)return;mutate(d=>({...d,items:[...d.items,{...sel,id:uid(),x:sel.x+200,y:sel.y+200}]}))};
 const downWallEnd=(e,w,end)=>{e.stopPropagation();setTool("select");setSelected({kind:"wall",id:w.id});setWallDrag({id:w.id,end,start:JSON.stringify(doc)})};
 const moveWallEnd=e=>{if(!wallDrag)return;const p=point(e),q={x:snapTo(p.x,doc.snapSize||50),y:snapTo(p.y,doc.snapSize||50)};setDoc(d=>{const target=d.walls.find(w=>w.id===wallDrag.id);if(!target)return d;const ox=wallDrag.end===1?target.x1:target.x2,oy=wallDrag.end===1?target.y1:target.y2;const walls=d.walls.map(w=>{let n={...w};if(w.id===wallDrag.id){if(wallDrag.end===1){n.x1=q.x;n.y1=q.y}else{n.x2=q.x;n.y2=q.y}}else{if(Math.hypot(w.x1-ox,w.y1-oy)<5){n.x1=q.x;n.y1=q.y}if(Math.hypot(w.x2-ox,w.y2-oy)<5){n.x2=q.x;n.y2=q.y}}return n});return {...d,walls,items:syncMounted(walls,d.items)}})};
 const endWallDrag=()=>{if(!wallDrag)return;setHistory(h=>[...h.slice(-24),wallDrag.start]);setFuture([]);setWallDrag(null)};
 const downItem=(e,o)=>{e.stopPropagation();setTool("select");setSelected({kind:"item",id:o.id});const p=point(e);setDrag({id:o.id,dx:p.x-o.x,dy:p.y-o.y,start:JSON.stringify(doc)})};
 const move=e=>{if(panning){movePan(e);return}if(wallDrag){moveWallEnd(e);return}if(!drag)return;const p=point(e);setDoc(d=>({...d,items:d.items.map(o=>o.id===drag.id?{...o,x:snapTo(p.x-drag.dx,d.snapSize||50),y:snapTo(p.y-drag.dy,d.snapSize||50)}:o)}))};
 const up=()=>{if(panning){setPanning(null);return}if(wallDrag){endWallDrag();return}if(!drag)return;setHistory(h=>[...h.slice(-24),drag.start]);setFuture([]);setDoc(d=>{const o=d.items.find(x=>x.id===drag.id);if(!o||!wallTypes.has(o.type))return d;const n=nearestWall({x:o.x+o.w/2,y:o.y+o.h/2},d.walls);if(!n||n.dist>450)return d;const a=Math.atan2(n.wall.y2-n.wall.y1,n.wall.x2-n.wall.x1)*180/Math.PI;return {...d,items:d.items.map(x=>x.id!==o.id?x:{...x,x:n.x-o.w/2,y:n.y-o.h/2,rot:a,wallId:n.wall.id})}});setDrag(null)};
 const canvasDown=e=>{if(e.target.dataset?.canvas!=="yes")return;if(tool==="pan"){startPan(e);return}setSelected(null);const p=point(e),q={x:snapTo(p.x,doc.snapSize||50),y:snapTo(p.y,doc.snapSize||50)};if(tool==="measure"){if(!measureDraft)setMeasureDraft(q);else{mutate(d=>({...d,measurements:[...(d.measurements||[]),{id:uid(),x1:measureDraft.x,y1:measureDraft.y,x2:q.x,y2:q.y}]}));setMeasureDraft(null)}return}if(tool!=="wall")return;if(!draft)setDraft(q);else{mutate(d=>({...d,walls:[...d.walls,{id:uid(),x1:draft.x,y1:draft.y,x2:q.x,y2:q.y,t:98,h:2400}]}));setDraft(q)}};
 const summary=useMemo(()=>{const wallM=doc.walls.reduce((s,w)=>s+len(w),0)/1000,wallM2=doc.walls.reduce((s,w)=>s+len(w)*(w.h||2400),0)/1000000,deckM2=doc.items.filter(o=>o.type==="deck").reduce((s,o)=>s+o.w*o.h,0)/1000000;const count=t=>doc.items.filter(o=>o.type===t).length;return {wallM,wallM2,deckM2,objects:doc.items.length,doors:count("door")+count("sliding"),windows:count("window"),posts:count("post")}},[doc]);
 const clearMeasures=()=>mutate(d=>({...d,measurements:[]}));
 const importJson=e=>{const file=e.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(String(r.result));if(!Array.isArray(x.walls)||!Array.isArray(x.items))throw new Error();const next={...initial(),...x,id:uid(),name:(x.name||"Importert tegning")+" – kopi"};setDoc(next);setSelected(null);setHistory([]);setMessage("Importert – trykk Lagre")}catch{alert("Filen ser ikke ut som en gyldig Aadland-tegning.")}};r.readAsText(file);e.target.value=""};
 const deleteDoc=async()=>{if(!confirm("Slette denne tegningen?"))return;if(doc.serverId){try{const r=await fetch("/api/admin/project-drawings",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:doc.serverId})});const x=await r.json();if(!r.ok&&!x.setupRequired){setMessage("Kunne ikke slette fra oppdraget");return}}catch{setMessage("Server utilgjengelig");return}}const list=docs.filter(x=>x.id!==doc.id);setDocs(list);localStorage.setItem(STORE,JSON.stringify(list));setDoc(list[0]||initial());setSelected(null);setHistory([]);setFuture([])};
 const exportJson=()=>{const blob=new Blob([JSON.stringify(doc,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=(doc.name||"tegning").replace(/[^a-z0-9æøå]+/gi,"-")+".json";a.click();URL.revokeObjectURL(a.href)};
 return <main className={styles.shell}>
  <header className={styles.top}><Link href="/admin">← Backoffice</Link><strong>Tegning & visualisering</strong><input className={styles.name} value={doc.name} onChange={e=>setDoc(d=>({...d,name:e.target.value}))}/><span className={styles.saved}>{message}</span><button className={styles.btn} onClick={()=>persist()}>Lagre</button><button className={styles.btn} onClick={undo} disabled={!history.length}>Angre</button><button className={styles.btn} onClick={redo} disabled={!future.length}>Gjør om</button><button className={styles.btn} onClick={()=>zoomBy(-.25)}>−</button><span className={styles.zoom}>{Math.round((doc.zoom||1)*100)}%</span><button className={styles.btn} onClick={()=>zoomBy(.25)}>+</button><button className={styles.btn} onClick={fitView}>Tilpass</button><button className={tool==="pan"?styles.activeBtn:styles.btn} onClick={()=>{setTool(tool==="pan"?"select":"pan");setDraft(null);setMeasureDraft(null)}}>Flytt visning</button><button className={styles.btn} onClick={()=>window.print()}>PDF</button></header>
  <div className={styles.layout}>
   <aside className={styles.panel}>
    <div className={styles.group}><h2>Tegninger</h2><div className={styles.row}><button className={styles.btn} onClick={newDoc}>+ Ny</button><button className={styles.btn} onClick={exportJson}>Eksporter</button><label className={styles.btn}>Importer<input className={styles.hiddenFile} type="file" accept="application/json,.json" onChange={importJson}/></label><button className={styles.btn+" "+styles.danger} onClick={deleteDoc}>Slett</button></div>{docs.length>0&&<select className={styles.select} value={doc.id} onChange={e=>openDoc(e.target.value)}>{docs.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select>}<div className={styles.field}><label>Koble til oppdrag</label><select className={styles.select} value={doc.projectId||""} onChange={changeProject}><option value="">Ikke koblet</option>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></div><div className={styles.field}><label>Kunde</label><input value={doc.customer||""} onChange={e=>setDoc(d=>({...d,customer:e.target.value}))}/></div><div className={styles.field}><label>Adresse</label><input value={doc.address||""} onChange={e=>setDoc(d=>({...d,address:e.target.value}))}/></div><div className={styles.field}><label>Notater</label><textarea className={styles.textarea} value={doc.notes||""} onChange={e=>setDoc(d=>({...d,notes:e.target.value}))}/></div></div>
    <div className={styles.group}><h2>Innstillinger</h2><div className={styles.field}><label>Snap/rutenett</label><select className={styles.select} value={doc.snapSize||50} onChange={e=>setDoc(d=>({...d,snapSize:Number(e.target.value)}))}><option value="10">10 mm</option><option value="25">25 mm</option><option value="50">50 mm</option><option value="100">100 mm</option></select></div><div className={styles.field}><label>PDF-målestokk</label><select className={styles.select} value={doc.scale||"1:50"} onChange={e=>setDoc(d=>({...d,scale:e.target.value}))}><option>1:20</option><option>1:25</option><option>1:50</option><option>1:100</option></select></div><label className={styles.check}><input type="checkbox" checked={doc.showGrid!==false} onChange={e=>setDoc(d=>({...d,showGrid:e.target.checked}))}/> Vis rutenett</label></div><div className={styles.group}><h2>Rom og vegger</h2><div className={styles.row}><button className={tool==="wall"?styles.activeBtn:styles.btn} onClick={()=>{setTool("wall");setDraft(null)}}>Tegn vegg</button><button className={styles.btn} onClick={makeRoom}>Rom etter mål</button><button className={tool==="measure"?styles.activeBtn:styles.btn} onClick={()=>{setTool("measure");setDraft(null);setMeasureDraft(null)}}>Mål avstand</button><button className={styles.btn} onClick={clearMeasures}>Fjern mål</button></div><p className={styles.muted}>Vegger følger valgt snap-oppløsning. Velg en vegg for å dra endepunktene; sammenkoblede vegghjørner flyttes samtidig. Klikk fortløpende punkter for sammenhengende vegger. Lengde og vinkel kan finjusteres eksakt.</p></div>
    {catalog.map(g=><div className={styles.group} key={g.group}><h2>{g.group}</h2><div className={styles.library}>{g.items.map(([t,l,w,h])=><button key={t} onClick={()=>addItem(t,w,h)}>{l}<small>{w} × {h} mm</small></button>)}</div></div>)}
   </aside>
   <section className={styles.workspace}><div className={styles.printHead}><h1>{doc.name}</h1><p>{[doc.customer,doc.address].filter(Boolean).join(" · ")}</p><p>Målestokk: {doc.scale||"1:50"} · Alle mål i mm · Aadland Service</p></div><div className={styles.canvasWrap}><svg ref={svg} className={styles.canvas} viewBox={pan.x+" "+pan.y+" "+viewSize+" "+viewSize} onPointerDown={canvasDown} onPointerMove={move} onPointerUp={up} onPointerLeave={up} onWheel={e=>{e.preventDefault();zoomBy(e.deltaY<0?.15:-.15)}}>
    <defs><pattern id="minor" width={GRID} height={GRID} patternUnits="userSpaceOnUse"><path d={"M "+GRID+" 0 L 0 0 0 "+GRID} fill="none" stroke="#ece9e1" strokeWidth="6"/></pattern><pattern id="major" width="1000" height="1000" patternUnits="userSpaceOnUse"><rect width="1000" height="1000" fill="url(#minor)"/><path d="M1000 0L0 0 0 1000" fill="none" stroke="#d9d5ca" strokeWidth="12"/></pattern></defs>
    <rect data-canvas="yes" width={VIEW} height={VIEW} fill={doc.showGrid===false?"#fff":"url(#major)"}/>
    {doc.walls.map(w=><g key={w.id} onPointerDown={e=>{e.stopPropagation();setTool("select");setSelected({kind:"wall",id:w.id})}} className={styles.pick}><line x1={w.x1} y1={w.y1} x2={w.x2} y2={w.y2} stroke={selected?.id===w.id?"#9b7a39":"#222"} strokeWidth={Math.max(35,w.t)} strokeLinecap="square"/>{selected?.kind==="wall"&&selected.id===w.id&&<><circle cx={w.x1} cy={w.y1} r="70" fill="#fff" stroke="#9b7a39" strokeWidth="22" onPointerDown={e=>downWallEnd(e,w,1)}/><circle cx={w.x2} cy={w.y2} r="70" fill="#fff" stroke="#9b7a39" strokeWidth="22" onPointerDown={e=>downWallEnd(e,w,2)}/></>}{(()=>{const d=dim(w);return <><line x1={d.ax} y1={d.ay} x2={d.bx} y2={d.by} stroke="#777" strokeWidth="10"/><line x1={d.ax-d.nx*60} y1={d.ay-d.ny*60} x2={d.ax+d.nx*60} y2={d.ay+d.ny*60} stroke="#777" strokeWidth="10"/><line x1={d.bx-d.nx*60} y1={d.by-d.ny*60} x2={d.bx+d.nx*60} y2={d.by+d.ny*60} stroke="#777" strokeWidth="10"/><text x={d.mx} y={d.my} textAnchor="middle" fontSize="105">{len(w)} mm · {angle(w)}°</text></>})()}</g>)}
    {doc.items.map(o=><g key={o.id} transform={"translate("+o.x+" "+o.y+") rotate("+o.rot+" "+o.w/2+" "+o.h/2+")"} onPointerDown={e=>downItem(e,o)} className={styles.pick}>{o.type==="door"?<g transform={o.flip?"translate("+o.w+" 0) scale(-1 1)":undefined}><line x1="0" y1={o.h/2} x2={o.w} y2={o.h/2} stroke="#51462f" strokeWidth="28"/><path d={"M0 "+o.h/2+" A "+o.w+" "+o.w+" 0 0 1 "+o.w+" "+(o.h/2-o.w)} fill="none" stroke="#8b806a" strokeWidth="18"/></g>:o.type==="sliding"?<><rect width={o.w} height={Math.max(o.h,100)} fill="#f7f7f7" stroke="#51462f" strokeWidth="18"/><line x1="60" y1="20" x2={o.w*.62} y2="20" stroke="#51462f" strokeWidth="22"/><line x1={o.w*.38} y1={o.h-20} x2={o.w-60} y2={o.h-20} stroke="#51462f" strokeWidth="22"/></>:o.type==="opening"?<><line x1="0" y1={o.h/2} x2={o.w} y2={o.h/2} stroke="#fff" strokeWidth="100"/><line x1="0" y1="0" x2="0" y2={o.h} stroke="#777" strokeWidth="16"/><line x1={o.w} y1="0" x2={o.w} y2={o.h} stroke="#777" strokeWidth="16"/></>:o.type==="window"?<><rect width={o.w} height={Math.max(o.h,100)} fill="#dfeef1" stroke="#51462f" strokeWidth="18"/><line x1="0" y1={o.h/2} x2={o.w} y2={o.h/2} stroke="#64828a" strokeWidth="18"/></>:<rect width={o.w} height={o.h} rx="30" fill={selected?.id===o.id?"#eadcbf":"#f5f1e7"} stroke="#51462f" strokeWidth="18"/>}<text x={o.w/2} y={o.h/2} textAnchor="middle" dominantBaseline="middle" fontSize="100">{labelFor(o.type)}</text><text x={o.w/2} y={o.h/2+125} textAnchor="middle" fontSize="75">{o.w} × {o.h}</text></g>)}
    {(doc.measurements||[]).map(m=><g key={m.id}><line x1={m.x1} y1={m.y1} x2={m.x2} y2={m.y2} stroke="#326a76" strokeWidth="12" strokeDasharray="35 22"/><circle cx={m.x1} cy={m.y1} r="28" fill="#326a76"/><circle cx={m.x2} cy={m.y2} r="28" fill="#326a76"/><text x={(m.x1+m.x2)/2} y={(m.y1+m.y2)/2-70} textAnchor="middle" fontSize="90" fill="#326a76">{Math.round(Math.hypot(m.x2-m.x1,m.y2-m.y1))} mm</text></g>)}{draft&&<><circle cx={draft.x} cy={draft.y} r="55" fill="#9b7a39"/><text x={draft.x+90} y={draft.y-80} fontSize="90">Neste veggpunkt</text></>}{measureDraft&&<><circle cx={measureDraft.x} cy={measureDraft.y} r="45" fill="#326a76"/><text x={measureDraft.x+80} y={measureDraft.y-60} fontSize="85" fill="#326a76">Velg endepunkt</text></>}
   </svg></div></section>
   <aside className={styles.panel+" "+styles.right}><h2>Egenskaper</h2>{!sel?<p className={styles.muted}>Velg et objekt. Møbler og utstyr kan dras direkte i tegningen. Dører, vinduer, rekkverk og levegger fester seg automatisk til nærmeste vegg når du slipper dem.</p>:selected.kind==="wall"?<><h3>Vegg</h3>{[["Lengde (mm)","len",len(sel)],["Vinkel (grader)","angle",angle(sel)],["Tykkelse (mm)","t",sel.t],["Høyde (mm)","h",sel.h]].map(([l,k,v])=><div className={styles.field} key={k}><label>{l}</label><input type="number" value={v} onChange={e=>update(k,e.target.value)}/></div>)}</>:<><h3>{labelFor(sel.type)}</h3>{[["Bredde (mm)","w"],["Dybde/lengde (mm)","h"],["X-posisjon (mm)","x"],["Y-posisjon (mm)","y"],["Rotasjon (grader)","rot"]].map(([l,k])=><div className={styles.field} key={k}><label>{l}</label><input type="number" value={Math.round(sel[k])} onChange={e=>update(k,e.target.value)}/></div>)}{sel.wallId&&doc.walls.find(w=>w.id===sel.wallId)&&<div className={styles.field}><label>Avstand fra veggens start/hjørne (mm)</label><input type="number" min="0" max={len(doc.walls.find(w=>w.id===sel.wallId))} value={wallOffset(sel,doc.walls.find(w=>w.id===sel.wallId))} onChange={e=>update("wallOffset",e.target.value)}/><small className={styles.muted}>Gir nøyaktig plassering av dør/vindu langs veggen.</small></div>}<div className={styles.row}>{sel.type==="door"&&<button className={styles.btn} onClick={flipDoor}>Speil slagretning</button>}{sel.wallId&&<button className={styles.btn} onClick={detach}>Løsne fra vegg</button>}<button className={styles.btn} onClick={duplicate}>Dupliser</button></div></>} {sel&&<button className={styles.btn+" "+styles.danger} onClick={remove}>Slett valgt</button>}
    <div className={styles.group+" "+styles.ai}><h2>Tegningsinfo</h2><p className={styles.muted}>Målestokk for utskrift: <b>{doc.scale||"1:50"}</b><br/>Alle oppgitte mål er i millimeter.</p></div><div className={styles.group+" "+styles.ai}><h2>Mengder fra tegning</h2><p className={styles.muted}>Vegger: <b>{summary.wallM.toFixed(2)} lm</b><br/>Brutto veggflate: <b>{summary.wallM2.toFixed(2)} m²</b><br/>Terrassefelt: <b>{summary.deckM2.toFixed(2)} m²</b><br/>Dører/skyvedører: <b>{summary.doors}</b><br/>Vinduer: <b>{summary.windows}</b><br/>Stolper: <b>{summary.posts}</b><br/>Objekter totalt: <b>{summary.objects}</b></p></div><div className={styles.group+" "+styles.ai}><h2>AI-visualisering</h2><p className={styles.muted}>Klargjort for neste trinn: kundebilde + prosjektmål + tekstbeskrivelse → realistisk visualisering. AI-bildet skal lagres som illustrasjon, mens denne tegningen er målgrunnlaget.</p></div>
   </aside>
  </div>
 </main>
}